include:
  - mariadb.service.yaml
#  - postgres.service.yaml
#  - compose.local.yaml

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro
        networks:
          - devbox
    moodle:
        image: moodlehq/moodle-php-apache:$MOODLE_DOCKER_PHP_VERSION
        volumes:
          - moodledata:/var/www/moodledata
          - $MOODLE_DOCKER_WWWROOT:/var/www/html
        depends_on:
          - mariadb
        environment:
          - VIRTUAL_HOST=moodle.local
        networks:
          - devbox
    mail:
        image: axllent/mailpit:latest
        ports:
          - 8025:8025
        networks:
          - devbox
volumes:
    moodledata:
        external: true
networks:
  devbox:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/16
